# 关于Compose文件的具体说明，请参考以下链接：
# https://docs.docker.com/compose/compose-file/

version: "3.5"
services:
  # 数据库的各种配置参数，请参考以下链接：
  # https://github.com/piexlmax/gin-vue-admin/blob/master/QMPlusServer/db/qmplus.sql#L4-L8
  # https://github.com/piexlmax/gin-vue-admin/blob/master/QMPlusServer/static/config/config.json#L8-L14
  database:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./QMPlusServer/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Aa@6447985
      MYSQL_DATABASE: qmPlus
    user: root
