# Gin-Vue-Admin Global Configuration

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# jwt configuration
jwt:
  signing-key: 'qmPlus'

# mysql connect configuration
mysql:
  username: root
  password: 'Aa@6447985'
  path: '127.0.0.1:3306'
  db-name: 'qmPlus'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

# Postgresql connect configuration
postgresql:
  username: 'gorm'
  password: 'gorm'
  db-name: 'gorm'
  port: '9920'
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  max-idle-conns: 10
  max-open-conns: 10
  logger: false
  prefer-simple-protocol: true

# sqlite connect configuration
# sqlite需要gcc支持 windows用户需要自行安装gcc
sqlite:
  # path: 'file::memory:?cache=shared' # 内存模式
  path: 'db.db'
  max-idle-conns: 10
  max-open-conns: 10
  logger: true

# Sqlserver connect configuration
sqlserver:
  username: 'gorm'
  password: 'LoremIpsum86'
  db-name: 'gorm'
  path: 'localhost:9930'
  max-idle-conns: 10
  max-open-conns: 10
  logger: true

# oss configuration

# 切换本地与七牛云上传，分配头像和文件路径
localupload:
  local: false
  file-path: uploads/file

# 请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址
qiniu:
  access-key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
  secret-key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
  bucket: 'qm-plus-img'
  img-path: 'http://qmplusimg.henrongyi.top'

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

# system configuration
system:
  use-multipoint: false
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: "mysql"  # support mysql/postgresql/sqlite/sqlserver
  need-init-data: false
  error-to-email: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# zap logger configuration
zap:
  # 可使用 "debug", "info", "warn", "error", "dpanic", "panic", "fatal",
  level: 'info'
  # console: 控制台, json: json格式输出
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写, LowercaseColorLevelEncoder:小写带颜色,CapitalLevelEncoder: 大写, CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

email:
  email-from: 'xxx@163.com'
  email-nickname: 'test'
  email-secret: 'xxx'
  email-to: 'xxx@qq.com'
  email-host: 'smtp.163.com'
  email-port: 465
  email-is-ssl: true