# Gin-Vue-Admin Global Configuration

# casbin configuration
casbin:
    model-path: './resource/rbac_model.conf'

# jwt configuration
jwt:
    signing-key: 'qmPlus'

# postgres connect configuration
postgres:
    username: postgres
    password: 'qinmin@328'
    path: '10.10.10.138:5432'
    db-name: 'gin_vue_admin_postgres'
    config: 'sslmode=disable'
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: true

#sqlite 配置
sqlite:
    path: db.db
    log-mode: true
    config: 'loc=Asia/Shanghai'

# oss configuration
qiniu:
    access-key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
    secret-key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
    bucket: 'qm-plus-img'
    img-path: 'http://qmplusimg.henrongyi.top'
# redis configuration
redis:
    addr: '10.10.10.138:6379'
    password: ''
    db: 0

# system configuration
system:
    use-multipoint: false
    env: 'public'  # Change to "develop" to skip authentication for development mode
    addr: 8888
    db-type: "postgres"  # support postgres/sqlite

# captcha configuration
captcha:
    key-long: 4
    img-width: 120
    img-height: 40

# logger configuration
log:
    prefix: '[GIN-VUE-ADMIN]'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'
