aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  transfer-restart: true
  root: E:\gin-vue-admin
  server: /server
  server-api: /api/v1/autocode
  server-initialize: /initialize
  server-model: /model/autocode
  server-request: /model/autocode/request/
  server-router: /router/autocode
  server-service: /service/autocode
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: qmPlus
  signing-key: 67d683af-8da0-4384-bb67-1fcbdf3a5f6b
local:
  path: uploads/file
mysql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
pgsql:
  path: 127.0.0.1
  port: "5432"
  config: sslmode=disable TimeZone=Asia/Shanghai
  db-name: gva
  username: postgres
  password: Aa@6447985
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: pgsql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
zap:
  level: info
  format: console
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
